# To link both the services 

version: '3.8'
services:
  ui_backend:
    build: ./ui_backend
    ports:
      - "5000:5000"
  ai_backend:
    build: ./ai_backend
    ports:
      - "5001:5001"
